backend:
  name: github
  repo: iDecal/catdecal
  branch: main
  base_url: https://decap-cms-proxy-gateway.vercel.app
  auth_endpoint: auth

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "services"
    label: "Dịch vụ Decal"
    folder: "src/content/services"
    create: true
    fields:
      - { label: "Tên dịch vụ", name: "title", widget: "string" }
      - { label: "Mô tả SEO", name: "description", widget: "string" }
      - { label: "Ảnh đại diện", name: "featured_image", widget: "image" }
      - { label: "Nội dung chi tiết", name: "body", widget: "markdown" }
